from docx import Document
from docx.shared import Pt, Inches, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT

doc = Document("MyCircle_Report_TEMP.docx")

def h(level, text):
    p = doc.add_paragraph()
    p.paragraph_format.space_before = Pt(12)
    p.paragraph_format.space_after = Pt(6)
    run = p.add_run(text)
    run.bold = True
    run.font.name = 'Times New Roman'
    run.font.size = Pt(max(12, 18 - level * 2))
    return p

def body(text):
    p = doc.add_paragraph(text)
    p.style = doc.styles['Normal']
    p.paragraph_format.first_line_indent = Cm(1)
    p.paragraph_format.space_after = Pt(6)
    p.paragraph_format.line_spacing = Pt(18)
    p.paragraph_format.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
    for run in p.runs:
        run.font.name = 'Times New Roman'
        run.font.size = Pt(12)
    return p

# CHAPTER 5
h(1, "CHAPTER 5: TECHNOLOGY STACK")

h(2, "5.1 MongoDB")
body("MongoDB is an open-source, cross-platform, document-oriented NoSQL database management system developed by MongoDB, Inc. Unlike traditional relational databases such as MySQL or PostgreSQL, which organize data into fixed-schema tables composed of rows and columns, MongoDB stores data as flexible BSON (Binary JSON) documents within collections. Each document is a self-contained JSON-like object that can have its own structure, allowing different documents within the same collection to have different fields. This schema flexibility is particularly valuable for a rapidly evolving application like MyCircle, where the opportunity post structure evolved significantly during development—adding fields like budgetMin, budgetMax, acceptsBarter, isUrgent, and coordinates—without requiring any database migration scripts or schema alteration commands.")
body("For MyCircle, MongoDB was chosen over relational alternatives for three primary reasons. First, the data model of an opportunity post maps naturally to a document: a post has nested sub-objects (coordinates), arrays of primitives (tags, images, likes), and optional fields—all of which are elegantly represented as a single document rather than spread across multiple joined tables. Second, MongoDB's horizontal scaling architecture (sharding) and cloud-native offering (MongoDB Atlas) make it straightforward to scale from the small dataset of an initial launch to millions of documents without architectural changes. Third, the JavaScript/JSON alignment between MongoDB's document format and the Node.js/React application layers reduces the conceptual impedance mismatch, allowing developers to use the same data structures from the database through the API to the UI.")
body("Mongoose, the ODM used to interface with MongoDB from Node.js, adds a structured application-level schema layer on top of MongoDB's flexible storage. Each Mongoose Schema defines the expected fields, their data types, validation rules, default values, and pre/post middleware hooks. For example, the Post schema defines the 'expiresAt' field as a Date, ensures 'title' is required and has a maximum length of 200 characters, and uses a pre-save hook to automatically compute the expiresAt value from createdAt and duration. MongoDB Atlas, MongoDB's fully managed cloud database service, hosts the MyCircle database, providing automatic daily backups, a free tier sufficient for development and early production, and a connection string that can be easily configured via environment variables.")

h(2, "5.2 Express.js")
body("Express.js is a minimal, unopinionated web application framework for Node.js, designed to simplify the process of building server-side web applications and RESTful APIs. It provides a thin abstraction over Node.js's built-in HTTP module, adding essential capabilities such as routing, middleware composition, request/response object enhancements, and error handling, while leaving architectural decisions (like project structure and state management) entirely to the developer. This minimalism makes Express.js an excellent choice for building clean, modular REST APIs where the developer retains full control over the application's architecture.")
body("The MyCircle Express.js server is organized using a layered architecture. The entry point (server.js) initializes the Express application, registers global middleware (CORS, body-parser for JSON, cookie-parser), establishes the MongoDB connection via Mongoose, initializes the Socket.io server on the same HTTP instance, and mounts the API routers. Each resource (auth, users, posts, conversations, notifications, requests, admin) has a dedicated router file that maps HTTP methods and URL patterns to controller functions. Controller functions handle the business logic for each route: they validate inputs, interact with Mongoose models, and return appropriate HTTP status codes and JSON response bodies. A centralized error-handling middleware at the bottom of the middleware stack catches any unhandled errors thrown by route handlers and formats them into consistent error response objects, preventing unhandled promise rejections from crashing the server.")
body("The middleware architecture of the Express.js server in MyCircle follows a pipeline pattern. An incoming request passes sequentially through: (1) CORS middleware—validates the request origin against the allowed origins list; (2) Body Parser—parses the JSON request body into req.body; (3) Auth Middleware (on protected routes)—extracts and verifies the JWT from the Authorization header, attaches the decoded user object to req.user; (4) Route Handler / Controller—executes the business logic; (5) Response—sends the JSON response with the appropriate HTTP status code. If any middleware calls next(error), the request skips to the centralized error handler, which logs the error and sends a standardized error response.")

h(2, "5.3 React.js")
body("React.js is an open-source JavaScript library developed by Meta for building user interfaces, particularly Single Page Applications (SPAs). React's core innovation is its component-based architecture, in which the UI is decomposed into small, reusable, self-contained components, each managing its own state and rendering logic. Components are composed into a tree hierarchy, and React's reconciliation algorithm (the Virtual DOM) efficiently updates only the parts of the actual DOM that have changed when state or props change, delivering high performance even in complex UIs.")
body("In MyCircle, the React component hierarchy is organized as follows. The root App component renders the React Router configuration, wrapping all routes in a set of context providers (AuthContext, ThemeContext, ToastContext, SocketContext, CurrencySymbolContext). The router renders page-level components (Explore, PostDetails, Profile, Messages, Admin, etc.) based on the current URL. Page components compose UI components (PostCard, Button, Modal, Toast, etc.) from the shared component library. This hierarchical structure ensures that global state (authentication status, theme preference, socket connection) is available to any component in the tree via Context, while local state (form inputs, modal visibility, expanded card state) is managed at the appropriate component level using useState.")
body("React hooks are used extensively throughout MyCircle. useState manages all local component state. useEffect handles side effects such as API data fetching on component mount and socket event subscription/unsubscription. useContext consumes global contexts (useAuth, useToast, useSocket). useCallback memoizes event handler functions to prevent unnecessary re-renders of child components. useMemo memoizes expensive computations (such as the lifecycle metadata calculation in PostCard). Custom hooks (useDialog, useCurrencySymbol) encapsulate reusable stateful logic. React Router v6's useNavigate and useParams hooks are used for programmatic navigation and URL parameter extraction respectively.")

h(2, "5.4 Node.js")
body("Node.js is an open-source, cross-platform JavaScript runtime environment built on Chrome's V8 JavaScript engine. Its defining characteristic is a non-blocking, event-driven I/O model that allows it to handle thousands of concurrent connections efficiently without creating a new thread for each connection—unlike traditional multi-threaded server environments like Apache HTTP Server with PHP. This architecture makes Node.js particularly well-suited to I/O-bound applications such as RESTful API servers, where the server spends most of its time waiting for database queries, file system operations, or external API calls to complete.")
body("For MyCircle, Node.js was the natural choice as the backend runtime for several reasons. Most fundamentally, it allows the entire application—both frontend and backend—to be written in JavaScript, reducing the cognitive overhead of context-switching between languages and enabling code sharing (for example, validation utility functions and constants can theoretically be shared between the client and server). The npm (Node Package Manager) ecosystem provides access to a vast library of open-source packages, including all the dependencies used in MyCircle (Express, Mongoose, jsonwebtoken, bcryptjs, Cloudinary SDK, Socket.io, etc.). The package.json file defines the project's metadata, dependency list, and npm scripts (npm run dev for development with nodemon auto-reload, npm start for production).")

h(2, "5.5 Vite")
body("Vite is a next-generation frontend build tool developed by Evan You (the creator of Vue.js) that addresses the performance limitations of traditional bundler-based development tools like Create React App (which uses Webpack). Vite's fundamental innovation is its two-speed architecture: during development, it leverages the browser's native ES Module (ESM) support to serve source files directly to the browser without bundling, enabling near-instantaneous server startup and blazing-fast Hot Module Replacement (HMR). In production, Vite uses Rollup (a highly optimized bundler) to generate efficient, tree-shaken, code-split production bundles.")
body("In the context of MyCircle, Vite dramatically improved the development experience compared to what Create React App would have provided. The development server starts in under 500 milliseconds regardless of the number of modules in the project, and HMR updates—where the browser instantly reflects code changes without a full page reload and without losing component state—typically complete in under 100 milliseconds. This fast feedback loop accelerated the UI development and debugging process significantly. Vite's production build generates an optimized bundle with automatic code-splitting (separate chunks for vendor libraries like React, Framer Motion, Leaflet, and the application code) and tree-shaking (removal of unused code from dependencies), resulting in smaller initial download sizes and faster page load times for end users.")

h(2, "5.6 Tailwind CSS")
body("Tailwind CSS is a utility-first CSS framework that provides a comprehensive set of pre-defined CSS utility classes, each doing one specific thing (e.g., 'flex' applies 'display: flex', 'p-4' applies 'padding: 1rem', 'text-blue-500' applies a specific shade of blue as the text colour). Instead of writing custom CSS classes with multiple properties, developers compose UI by applying utility classes directly in their JSX markup. This approach eliminates the need for a separate CSS file for most component styling and prevents specificity conflicts and dead CSS accumulation.")
body("MyCircle uses Tailwind CSS as its primary styling system, customized via the tailwind.config.js file to define the application's design tokens: a dark-mode-first colour palette with custom variables (--color-primary, --color-card, --color-background-secondary, etc.), custom border radii, custom font families (Inter), and custom animation keyframes. The responsive design is implemented using Tailwind's breakpoint prefixes (sm:, md:, lg:) applied directly to utility classes in JSX, enabling mobile-first responsive layouts without writing any media query CSS manually. The dark mode is toggled via a class applied to the HTML root element, which Tailwind detects to apply dark: variant classes.")

h(2, "5.7 JWT Authentication")
body("JSON Web Tokens (JWT) are an open standard (RFC 7519) for securely transmitting information between parties as a JSON object. A JWT consists of three Base64URL-encoded parts separated by dots: the Header (specifying the algorithm and token type), the Payload (containing the claims—in MyCircle's case, the user's _id and role), and the Signature (a cryptographic hash of the header and payload using a secret key). The signature ensures that the token has not been tampered with.")
body("In MyCircle's authentication flow, the sequence is as follows. The user submits their email and password to POST /api/auth/login. The server looks up the user by email, compares the submitted password against the stored bcrypt hash using bcrypt.compare(). If the comparison succeeds, the server generates a JWT using jwt.sign({ userId: user._id, role: user.role }, process.env.JWT_SECRET, { expiresIn: '7d' }). The token is returned to the client in the login response body. The React application stores the JWT in localStorage and attaches it to all subsequent API requests via an Axios request interceptor that automatically adds the Authorization: Bearer <token> header. On the server, the auth middleware extracts the token from this header, verifies it using jwt.verify(), and attaches the decoded payload to req.user, making the authenticated user's ID and role available to all route handlers in the request pipeline. Passwords are hashed using bcryptjs with a salt rounds value of 10, ensuring that even if the database is compromised, raw passwords cannot be trivially recovered.")

h(2, "5.8 Axios")
body("Axios is a popular promise-based HTTP client for JavaScript, available for both the browser and Node.js. In the MyCircle React application, Axios is configured as a singleton instance in the api.js utility file. This singleton sets the baseURL to the API server's URL (from an environment variable), allowing all API calls throughout the application to use relative paths (e.g., api.get('/posts') rather than specifying the full URL each time). An Axios request interceptor is registered on this instance to automatically attach the Authorization: Bearer <token> header to every outgoing request if a JWT is present in localStorage, eliminating the need to manually include the token in each individual API call. A response interceptor handles 401 Unauthorized responses globally, automatically logging out the user and redirecting them to the login page if their JWT has expired or been invalidated.")

h(2, "5.9 Socket.io")
body("Socket.io is a JavaScript library that enables real-time, bidirectional, event-based communication between clients and servers. It builds on the WebSocket protocol, with automatic fallback to HTTP long-polling for environments where WebSockets are not supported. In MyCircle, Socket.io is used to deliver two categories of real-time events: direct message delivery (a message sent by one user is instantly pushed to the recipient's browser without polling) and notification delivery (when a user follows another user, likes a post, or sends a message, the recipient receives an in-app notification in real time).")
body("The Socket.io server is initialized on the same HTTP server instance as the Express.js application. Upon connection, each authenticated client emits a 'join' event with their user ID, and the server adds their socket to a room named by their user ID. This allows the server to emit targeted events to a specific user's room (e.g., io.to(recipientUserId).emit('new_message', messageData)) without broadcasting to all connected clients. The React frontend connects to the Socket.io server via the SocketContext, which maintains a single socket connection for the authenticated session and exposes it to any component via the useSocket hook.")

h(2, "5.10 Cloudinary")
body("Cloudinary is a cloud-based media management platform that provides services for image and video upload, storage, transformation, optimization, and delivery via a global CDN. In MyCircle, Cloudinary handles all user-generated image assets: profile photographs and opportunity post images. The image upload flow works as follows: the user selects an image in the React UI, which sends a multipart/form-data POST request to the Express.js server. The server uses Multer middleware to receive the file in memory (as a buffer), then calls the Cloudinary SDK's upload_stream() method to upload the buffer to Cloudinary. Cloudinary stores the image, applies automatic optimization (format conversion to WebP for modern browsers, quality compression), and returns a JSON response containing the secure CDN URL of the uploaded image. This URL is then stored in the MongoDB document (profileImage field for users, images array for posts). When the React frontend renders the image, it requests it directly from Cloudinary's global CDN, ensuring fast delivery regardless of the user's geographic location.")

h(2, "5.11 Git & GitHub")
body("Git is a distributed version control system used to track changes in the MyCircle codebase throughout the development process. Every significant feature or bug fix was committed with a descriptive commit message, creating a complete audit trail of the project's evolution. GitHub was used as the remote repository hosting platform, providing a centralized location for the codebase, enabling collaboration, and serving as the deployment trigger for the cloud hosting platform (Render automatically redeploys the server when new commits are pushed to the main branch). The repository is organized as a monorepo containing three sub-directories: mycircleappsuite/server (Express.js backend), mycircleappsuite/web (React frontend), and mycircleappsuite/mobile (React Native mobile app, future scope). Branching was used during development to isolate feature work—for example, a 'feature/map-view' branch was used during the Leaflet map integration to avoid destabilizing the main branch.")

doc.add_page_break()
doc.save("MyCircle_Report_TEMP.docx")
print("Part 4 saved — Chapter 5 complete.")
